sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t dschuemann/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t dschuemann/multi-client ./client
  - docker build -t dschuemann/multi-nginx ./nginx
  - docker build -t dschuemann/multi-server ./server
  - docker build -t dschuemann/multi-worker ./worker

  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker hub
  - docker push dschuemann/multi-client
  - docker push dschuemann/multi-nginx
  - docker push dschuemann/multi-server
  - docker push dschuemann/multi-worker